### ISSUE TITLE
Data structure for graph

### ISSUE THREAD

**Issue by Claudia4** [Claudia4/Traveling-Salesman#1]
What data structure will we use for the graph and the weights?
* Make sure that it is easy to derive G-v_1 and c_\lambda
* How will R and F as subsets of edges be saved? It should be easy to combine with the graph structure.

**Comment by Claudia4** [comment]
We decided to put the costs in a 'matrix', that is a vector of vectors.

I decided to use entries of type double, even though the initial costs are rounded to integers. This is because all the c_\lambda will not be integer, so we would have to use double at some point, anyway.

**Comment by Claudia4** [comment]
An appropriate structur for edges is still open. Possibilities would be
- using std::pair
- creating an own struct (containing two ints) or even a class

**Comment by AnnaA11** [comment]
I think it is enough to use vectors of pairs for R and F.
