### ISSUE TITLE
Minimum spanning tree algorithm

### ISSUE THREAD

**Issue by Claudia4** [Claudia4/Traveling-Salesman#2]
Will we use Kruskal's or Prim's algorithm?

pro Kruskal: required edges can be used as basis for tree
con Kruskal: I'm not sure about runtime

pro Prim: runtime seems better
con Prim: how to enforce required edges?

**Comment by AnnaA11** [comment]
Prim is easier to implement using UnionFind. 
One can enforce edges by setting the costs to zero and forbid edges by setting the costs to infinity.

**Comment by AnnaA11** [comment]
sorry I meant Kruskal

**Comment by Claudia4** [comment]
Had to change to Prim because of runtime...
